import Link from "next/link";
import { loadCanonical } from "../../canonical";
import { CanonicalNetwork, CanonicalUnavailable } from "../../canonical-ui";
import { PageHeading } from "../../ui";

export default async function MandateDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const state = await loadCanonical();
  if (state.status === "UNAVAILABLE") return <><PageHeading eyebrow="Mandate detail" title={<span className="detail-id">{id}</span>} lede="Canonical mandate detail is read directly from the Intelligent Contract." action={<Link className="button secondary" href="/mandates">Back to mandates</Link>} /><CanonicalUnavailable error={state.error} /></>;
  const mandate = state.model.mandates.find((item) => item.mandateId === id);
  if (!mandate) return <><PageHeading eyebrow="Mandate detail" title={<span className="detail-id">{id}</span>} lede="Canonical mandate detail is read directly from the Intelligent Contract." action={<Link className="button secondary" href="/mandates">Back to mandates</Link>} /><div className="empty"><strong>Canonical mandate not found</strong>The live contract returned no record for {id}.</div></>;
  const executions = state.model.executions.filter((item) => item.mandateId === mandate.mandateId);
  return <><PageHeading eyebrow="Mandate detail" title={<span className="detail-id">{id}</span>} lede="This frozen governance intent is read directly from the canonical Intelligent Contract." action={<Link className="button secondary" href="/mandates">Back to mandates</Link>} /><CanonicalNetwork model={state.model} /><div className="panel"><div className="panel-header"><h2>Mandate record</h2><span className="status safe"><span className="status-dot" />CANONICAL LIVE READ</span></div><div className="panel-body detail-grid"><div><span className="field-label">State</span><span>{mandate.state}</span></div><div><span className="field-label">Proposal</span><span>{mandate.proposalExternalId}</span></div><div><span className="field-label">Proposal text</span><span>{mandate.proposalText}</span></div><div><span className="field-label">Governance source</span><span className="mono">{mandate.proposalSource}</span></div><div><span className="field-label">Governance contract</span><span className="mono">{mandate.governanceContract}</span></div><div><span className="field-label">Mandate digest</span><span className="mono">{mandate.mandateDigest}</span></div></div></div><div className="panel" style={{ marginTop: 18 }}><div className="panel-header"><h2>Bound execution packages</h2></div>{executions.length === 0 ? <div className="empty"><strong>No executions committed</strong>The live contract returned no execution for this mandate.</div> : <div className="audit-list">{executions.map((execution) => <div className="audit-row" key={execution.executionId}><Link className="audit-id" href={`/executions/${execution.executionId}`}>{execution.executionId}</Link><div className="audit-kind">{execution.state} · {execution.semanticInput}</div><div className="audit-time">chain {execution.chainId}</div></div>)}</div>}</div></>;
}
